sudo: false
language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
- npm ci
- npm run build
- npm t
env:
  global:
  - secure: NSezO5me5lNt54t9u5mbCsxQeE98vENaFZRlELP3YMhW2xBaf+ZrJqSTkKHMAZKsU/Pg48WcDmmqcs8zFYTwyFFDBToFwHjRAZAWQi2fIFbekaWiG2vFgFW0bzBxn0q38hwDNaDX89E98ojeF6Wekhg0BlVXx89yStUgElBRC85ZdFKMvT1YaqIoqleGC9fXt/6s9aBbmaETltPl8Fq/uian9JStPSpsAOkrV44RSZtz0odNoYRwJVsg7yuocff1x3DiLzhq8kc6V27RushHdtNtt0y1mvOoUt0CmUae29Jho/xrmbNCC+RO9APASqAEhqt6eBq80WuFFyrXqh/0FSZ0d4Gr5Q1BXZOmVEjhDgPQy4Zs5AG/rPcGCtN6M8r6pPFsmdl+6uPLvNdPr71PkdsNvwUv5+by3cNvXUPfftlnm/a/gOVxKBf2V8Z6YgJzHJBlQbJLPpc3psZ0nMXOivtggzr9BukMMqX1+az4qUClK7ETmycqxs9uiiOC/DRidZZieCEpXMn0mGy25JKT9OHHdIOV6PlRlVMkcfs+3qA+kaTuhvRS6X4LJ2giUli1JQ0rLVve7K5m75G1K1UMCxiJQdhFWJ7s5WuXdl5DQ88O80N+Pw/t2QhPBV0HLVMAmCS2NV9fUi9QrZaV9juoRIFbmHVRzG5j17pxZKj1kIY=
  - secure: e8ZcPeVYBukFeaJYKfWyvV3eWuORPD95OtqeihrtrLykfgjnUcA3MAaFMc1Mlb3XgVff4kc4IjB2ybTc/H5udwBpJf5I91a7K0qslrKJ0mXfN32yT7elQpFKNJUyr/VhPTHgh46nAJW280LLl1NWBVBTzsn9U0Nl8MBy4vhT4HWNbRbmfCYSsC9qbH+vUCgT2SdQSiUCZqXfp36GNr5YsIPCHzD8Oh0BN2B4GbGiV7E0hXskZzV3JoXYxEzhffbBJ3ITPkWLjRILQnqIoPe0RWY9i2o+7k4RWxZK/wkx9Qg7cO3rQvnT+3SbwwboICe6Mm5+B04OYBmos8ievTM6cuMXGXVCJ48LzX1ATWVJ0fVJpj/UzFJ1NLGMGj+cz0ysMWblDnkAC4ZgjdWLsqqR02o6w8uLhqKOMJQAZg4PsvP5pzH5vtKk92jijszqZNM2q0sNP7HUZOYS4HhNU5gxSSGoCeHwW8OqPk/IdIGjxSfEhIz7KWYlO7pHWu/oWfXDbKfKae9AXQJtlicJfNoCB60UTMkOuoLd+nhacvkBX5mH0isgjYvhZgKmXYZltPRn0pNCBPFn24T3n1FgiKUbQv09mbBIP71yl8R0hhKFTLY0aRWyluABZI2ufKB2NPi93gO/GiBSqNS/b0uoIqJHCntnmz0fFMQNHQm96+FD41Q=
